name: 'Action to test the action locally with act'
on:
  push:
    branches:
    - branch-that-does-not-exist

jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}

  test-json-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'test-file-new.json'

      - name: Show file
        id: show
        run: |
          echo "$(<test-file-new.json)"

  test-json-empty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - run: touch ./test-file-empty.json

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './test-file-empty.json'

      - run: echo "$(<./test-file-empty.json)"

  test-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - run: test -f pre-commit.test.json && (echo should not be here yet && exit 1) || exit 0

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          pre-commit: test/pre-commit.js
          skip-on-empty: 'false'

      - run: test -f pre-commit.test.json || (echo should be here && exit 1)
      - run: cat pre-commit.test.json

  test-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: 'true'

  test-git-fallback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"
      
      - run: git tag | xargs git tag -d

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: 'true'

  test-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'test-file.txt'
          version-path: 'package.version'

  test-txt-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - run: touch ./test-file-empty.txt

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'test-file-new.txt'
          version-path: 'package.version'

      - run: echo "$(<test-file-new.txt)"

  test-txt-empty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './test-file-empty.txt'
          version-path: 'package.version'

      - run: echo "$(<./test-file-empty.txt)"

  test-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'test-file.yaml'
          version-path: 'package.version'

  test-yaml-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - run: touch ./test-file-empty.yaml

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'test-file-new.yaml'
          version-path: 'package.version'

      - run: echo "$(<test-file-new.yaml)"

  test-yaml-empty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './test-file-empty.yaml'
          version-path: 'package.version'

      - run: echo "$(<./test-file-empty.yaml)"

  test-toml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'test-file.toml'
          version-path: 'package.version'

  test-toml-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'test-file-new.toml'
          version-path: 'package.version'

      - run: echo "$(<test-file-new.toml)"

  test-toml-empty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - run: touch ./test-file-empty.toml

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './test/test-file-empty.toml'
          version-path: 'package.version'

      - run: echo "$(<./test/test-file-empty.toml)"

  test-multiple-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Generate changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'package.json, package-lock.json'

  test-config-file-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "./"

      - name: Install Packages
        run: yarn

      - name: Generate Changelog
        id: changelog
        uses: ./
        env:
          ENV: 'dont-use-git'
        with:
          github-token: ${{ secrets.github_token }}
          skip-version-file: 'true'
          config-file-path: './test-changelog.config.js'
